version: '3.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
     - ./:/code/
     - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - code-network
  php:
    build: docker/php7
    volumes:
      - ./:/code/
      - ./docker/php7/xdebug.ini/:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - code-network
#    command: './setup'
  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cyber-duck-crm
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
